puts """
Each new term in the Fibonaccis sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3 , 5, 8, 13, 21, 34, 55, 89, ...
\nBy considering the terms in the Fibonacci sequence whose values do not exceed X, find the sum of the even-valued terms.
"""
print "Please enter X > "

input = gets.chomp.to_i

def fibonacci_number(input)
	a = 0
	b = 1
	fib = 1
	sol = 0
	for i in 1..input
		fib = a + b
		a = b
		b = fib
		if fib % 2 == 0
			sol += fib
		end
	end
	return sol
end

puts "The sum of even valued terms not exceeding #{input} is #{fibonacci_number(input)}"